### PR TITLE
Hello World test

### PR DESCRIPTION
**Pull request by jessica-writes-code**
@binghailing

### CODE REVIEW

**Comment by binghailing** [comment]
I made the graph generator into a function.  Would you like to review the code?  I didn't have a chance to test it because Stanford network issues.  And maybe we can merge it afterwards or something.  Still learning this git/github thing.

**Comment by jessica-writes-code** [comment]
I've looked at it quickly (but haven't tested it for the same reasons). I don't see any problems. Let's merge both my branch and yours at our meeting, assuming we have time.

Also, is b9_30tweets a complete 24 hours? or just a subset?

@poorna-kumar for viz.

**Comment by binghailing** [comment]
The data set does not exist yet, it's running at the moment, and it keeps crashing with the issue on Canvas (w/NoneType and strip).  It's a placeholder for now.  I'm not good enough to debug multithreaded stuff in python, otherwise, I think it would be easy to add an exception handler to ignore those lines.

**Comment by jessica-writes-code** [comment]
Huh. Interesting. I didn't run into that issue (for whatever reason). Can I take a look at the error later? Maybe the three of us can put our heads together and come up with something.

Also, I'll try running a filtered set tomorrow morning. Maybe my access to corn is just magical? Unfortunately, it'll be the weekend, so we may not see as interesting a trend for "coffee", but at least we'd have data and then we can rerun things at our leisure, if we really want something cool.

**Pull request merged**
